import request from './request'

export const login = data => request.post('/auth/login', data)
export const register = data => request.post('/auth/register', data)
export const me = () => request.get('/auth/me')
export const publicGroups = params => request.get('/groups/public/page', { params })
export const groups = params => request.get('/groups/page', { params })
export const joinedGroups = () => request.get('/groups/joined')
export const groupDetail = id => request.get(`/groups/${id}`)
export const saveGroup = data => data.id ? request.put('/groups', data) : request.post('/groups', data)
export const deleteGroup = id => request.delete(`/groups/${id}`)
export const reviewGroup = (id, auditStatus) => request.post(`/groups/${id}/review`, null, { params: { auditStatus } })
export const uploadImage = file => {
  const formData = new FormData()
  formData.append('file', file)
  return request.post('/upload/image', formData, { headers: { 'Content-Type': 'multipart/form-data' } })
}
export const groupMembers = id => request.get(`/groups/${id}/members`)
export const quitGroup = id => request.post(`/groups/${id}/quit`)
export const removeMember = (groupId, userId) => request.delete(`/groups/${groupId}/members/${userId}`)
export const applyJoin = data => request.post('/applies', data)
export const myApplies = () => request.get('/applies/mine')
export const groupApplies = groupId => request.get(`/applies/group/${groupId}`)
export const reviewApply = (id, data) => request.post(`/applies/${id}/review`, data)
export const activities = params => request.get('/activities/page', { params })
export const publicActivities = params => request.get('/activities/public/page', { params })
export const visibleActivities = params => request.get('/activities/visible', { params })
export const saveActivity = data => data.id ? request.put('/activities', data) : request.post('/activities', data)
export const deleteActivity = id => request.delete(`/activities/${id}`)
export const signupActivity = id => request.post(`/activities/${id}/signup`)
export const activitySignups = id => request.get(`/activities/${id}/signups`)
export const myActivitySignups = () => request.get('/activities/signups/mine')
export const reviewActivitySignup = (id, data) => request.post(`/activities/signups/${id}/review`, data)
export const categories = () => request.get('/categories')
export const saveCategory = data => data.id ? request.put('/categories', data) : request.post('/categories', data)
export const deleteCategory = id => request.delete(`/categories/${id}`)
export const notices = () => request.get('/notices/visible')
export const systemNotices = () => request.get('/notices/public/system')
export const allNotices = () => request.get('/notices')
export const managedNotices = () => request.get('/notices/managed')
export const saveNotice = data => data.id ? request.put('/notices', data) : request.post('/notices', data)
export const publishNotice = data => request.post('/notices', data)
export const deleteNotice = id => request.delete(`/notices/${id}`)
export const users = params => request.get('/users', { params })
export const setUserStatus = (id, status) => request.put(`/users/${id}/status`, null, { params: { status } })
export const stats = () => request.get('/stats/overview')
